'use strict';

const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} = require('node:fs');
const { tmpdir } = require('node:os');
const { join, resolve } = require('node:path');
const test = require('node:test');

const ROOT_HELPER = resolve(__dirname, '../.claude/helpers/intelligence.cjs');
const PACKAGE_HELPER = resolve(
  __dirname,
  '../v3/@claude-flow/cli/.claude/helpers/intelligence.cjs',
);

function init(root) {
  const script = [
    `const intelligence = require(${JSON.stringify(ROOT_HELPER)});`,
    'process.stdout.write(JSON.stringify(intelligence.init()));',
  ].join('');
  const stdout = execFileSync(process.execPath, ['-e', script], {
    cwd: root,
    env: { ...process.env, CLAUDE_PROJECT_DIR: root },
    encoding: 'utf-8',
    timeout: 2_000,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  return JSON.parse(stdout);
}

function consolidate(root) {
  const script = [
    `const intelligence = require(${JSON.stringify(ROOT_HELPER)});`,
    'process.stdout.write(JSON.stringify(intelligence.consolidate()));',
  ].join('');
  const stdout = execFileSync(process.execPath, ['-e', script], {
    cwd: root,
    env: { ...process.env, CLAUDE_PROJECT_DIR: root },
    encoding: 'utf-8',
    timeout: 2_000,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  return JSON.parse(stdout);
}

test('root and package intelligence helpers remain byte-identical', () => {
  assert.equal(readFileSync(ROOT_HELPER, 'utf-8'), readFileSync(PACKAGE_HELPER, 'utf-8'));
});

test('same-ID memory edits refresh the store and bypass the graph cache', () => {
  const root = mkdtempSync(join(tmpdir(), 'ruflo-intelligence-reconcile-'));
  const memoryDir = join(root, '.claude', 'memory');
  const memoryFile = join(memoryDir, 'MEMORY.md');
  const dataDir = join(root, '.claude-flow', 'data');
  const storeFile = join(dataDir, 'auto-memory-store.json');
  const rankedFile = join(dataDir, 'ranked-context.json');
  const originalBody = 'Original memory content remains stable for this cache test.';
  const updatedBody = 'Updated memory content is visible immediately after this edit.';

  try {
    mkdirSync(memoryDir, { recursive: true });
    writeFileSync(memoryFile, `# Stable Topic\n\n${originalBody}\n`, 'utf-8');

    const first = init(root);
    assert.equal(first.nodes, 1);

    const firstStore = JSON.parse(readFileSync(storeFile, 'utf-8'));
    assert.equal(firstStore.length, 1);
    const memoryId = firstStore[0].id;
    const createdAt = firstStore[0].createdAt;
    const preserved = {
      id: 'insight-preserved',
      key: 'preserved-non-memory-entry',
      content: 'A non-memory entry must survive memory-file reconciliation.',
      namespace: 'insights',
      type: 'procedural',
      metadata: { autoGenerated: true },
      createdAt: 123456789,
    };
    writeFileSync(storeFile, JSON.stringify([...firstStore, preserved]), 'utf-8');

    const withPreservedEntry = init(root);
    assert.equal(withPreservedEntry.nodes, 2);

    writeFileSync(memoryFile, `# Stable Topic\n\n${updatedBody}\n`, 'utf-8');
    const afterEdit = init(root);

    assert.notEqual(afterEdit.message, 'Graph cache hit');
    assert.equal(afterEdit.nodes, 2);

    const refreshedStore = JSON.parse(readFileSync(storeFile, 'utf-8'));
    const refreshedMemory = refreshedStore.find((entry) => entry.id === memoryId);
    assert.ok(refreshedMemory);
    assert.equal(refreshedMemory.content, updatedBody);
    assert.equal(refreshedMemory.createdAt, createdAt);
    assert.deepEqual(
      refreshedStore.find((entry) => entry.id === preserved.id),
      preserved,
    );

    const ranked = JSON.parse(readFileSync(rankedFile, 'utf-8'));
    assert.equal(ranked.entries.find((entry) => entry.id === memoryId).content, updatedBody);

    const stableStore = readFileSync(storeFile, 'utf-8');
    const unchanged = init(root);
    assert.equal(unchanged.message, 'Graph cache hit');
    assert.equal(readFileSync(storeFile, 'utf-8'), stableStore);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('consolidation persists same-ID memory edits', () => {
  const root = mkdtempSync(join(tmpdir(), 'ruflo-intelligence-consolidate-'));
  const memoryDir = join(root, '.claude', 'memory');
  const memoryFile = join(memoryDir, 'MEMORY.md');
  const dataDir = join(root, '.claude-flow', 'data');
  const storeFile = join(dataDir, 'auto-memory-store.json');
  const rankedFile = join(dataDir, 'ranked-context.json');
  const updatedBody = 'Consolidation persists this edited memory content into the store.';

  try {
    mkdirSync(memoryDir, { recursive: true });
    writeFileSync(
      memoryFile,
      '# Stable Consolidation Topic\n\nOriginal consolidation memory content.\n',
      'utf-8',
    );
    init(root);

    writeFileSync(memoryFile, `# Stable Consolidation Topic\n\n${updatedBody}\n`, 'utf-8');
    const result = consolidate(root);
    assert.equal(result.entries, 1);

    const store = JSON.parse(readFileSync(storeFile, 'utf-8'));
    const ranked = JSON.parse(readFileSync(rankedFile, 'utf-8'));
    assert.equal(store[0].content, updatedBody);
    assert.equal(ranked.entries[0].content, updatedBody);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
